/* Generated by gen_protocol.py - DO NOT EDIT DIRECTLY */
#pragma once

// Project: ThrillRig
// Version: 0.0.2

namespace THR_PROT {
    const char* const APP_VERSION = "0.0.2";
    const char* const CMD_DELIMITER = ":";
    const char* const DATA_DELIMITER = "|";

    // 게임 점수 투입
    const char* const CMD_CALL = "F13";

    // 배출 차단 제어
    const char* const CMD_CONTROL = "F14";

    // 응급 및 시스템 강제 제어
    const char* const CMD_EMERGENCY = "EMG";
    const char* const ACT_PC_RESET = "PC_RESET"; // 리부팅
    const char* const ACT_PC_OFF = "PC_OFF"; // 전원종료
    const char* const ACT_GAME_KILL = "GAME_KILL"; // 프로세스강제종료

    // 정산 데이터 보고
    const char* const CMD_STATICS = "STAT";

    // 과금 및 결제 트랜잭션
    const char* const CMD_BILLING = "BILL";

    // 메시지 수신 확인 응답
    const char* const CMD_ACK = "ACK";

}