import json
import os

# 1. 경로 설정 (현재 스크립트 위치 기준)
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(BASE_DIR)
JSON_PATH = os.path.join(BASE_DIR, 'Protocol.json')

# 각 프로그램별 타겟 경로 (프로젝트 루트 기준)
TARGETS = {
    'CPP': os.path.join(PROJECT_ROOT, 'TRAdapter', 'TR_Protocol.h'),
    'PYTHON': os.path.join(PROJECT_ROOT, 'TRBrain', 'TR_Protocol.py'),
    'PHP': os.path.join(PROJECT_ROOT, 'TRService', 'TR_Protocol.php')
}

def generate_cpp(data):
    lines = [
        "/* Generated by gen_protocol.py - DO NOT EDIT DIRECTLY */",
        "#pragma once",
        "",
        f"// Project: {data['project']}",
        f"// Version: {data['version']}",
        "",
        "namespace THR_PROT {",
        f"    const char* const APP_VERSION = \"{data['version']}\";",
        f"    const char* const CMD_DELIMITER = \"{data['settings']['cmd_delimiter']}\";",
        f"    const char* const DATA_DELIMITER = \"{data['settings']['data_delimiter']}\";",
        ""
    ]
    for key, signal in data['signals'].items():
        lines.append(f"    // {signal.get('description', '')}")
        lines.append(f"    const char* const CMD_{key} = \"{signal['id']}\";")
        if 'actions' in signal:
            for act_key, act_desc in signal['actions'].items():
                lines.append(f"    const char* const ACT_{act_key} = \"{act_key}\"; // {act_desc}")
        lines.append("")
    lines.append("}")
    return "\n".join(lines)

def generate_python(data):
    lines = [
        "# Generated by gen_protocol.py - DO NOT EDIT DIRECTLY",
        "",
        f"PROJECT = \"{data['project']}\"",
        f"APP_VERSION = \"{data['version']}\"",
        "",
        "class TRProtocol:",
        f"    APP_VERSION = \"{data['version']}\"",
        f"    CMD_DELIMITER = \"{data['settings']['cmd_delimiter']}\"",
        f"    DATA_DELIMITER = \"{data['settings']['data_delimiter']}\"",
        ""
    ]
    for key, signal in data['signals'].items():
        lines.append(f"    # {signal.get('description', '')}")
        lines.append(f"    CMD_{key} = \"{signal['id']}\"")
        if 'actions' in signal:
            for act_key, act_desc in signal['actions'].items():
                lines.append(f"    ACT_{act_key} = \"{act_key}\"  # {act_desc}")
        lines.append("")
    return "\n".join(lines)

def generate_php(data):
    lines = [
        "<?php",
        "/* Generated by gen_protocol.py - DO NOT EDIT DIRECTLY */",
        "",
        f"define('TR_PROJECT', '{data['project']}');",
        f"define('TR_APP_VERSION', '{data['version']}');",
        "",
        f"define('TR_CMD_DELIMITER', '{data['settings']['cmd_delimiter']}');",
        f"define('TR_DATA_DELIMITER', '{data['settings']['data_delimiter']}');",
        ""
    ]
    for key, signal in data['signals'].items():
        lines.append(f"// {signal.get('description', '')}")
        lines.append(f"define('TR_CMD_{key}', '{signal['id']}');")
        if 'actions' in signal:
            for act_key, act_desc in signal['actions'].items():
                lines.append(f"define('TR_ACT_{act_key}', '{act_key}'); // {act_desc}")
        lines.append("")
    lines.append("?>")
    return "\n".join(lines)

def main():
    if not os.path.exists(JSON_PATH):
        print(f"Error: {JSON_PATH} not found.")
        return
    with open(JSON_PATH, 'r', encoding='utf-8') as f:
        data = json.load(f)

    for lang, target_path in TARGETS.items():
        os.makedirs(os.path.dirname(target_path), exist_ok=True)
        content = ""
        if lang == 'CPP': content = generate_cpp(data)
        elif lang == 'PYTHON': content = generate_python(data)
        elif lang == 'PHP': content = generate_php(data)
        
        with open(target_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Generated: {target_path}")

if __name__ == "__main__":
    main()
