<?php
/* Generated by gen_protocol.py - DO NOT EDIT DIRECTLY */

define('TR_PROJECT', 'ThrillRig');
define('TR_APP_VERSION', '0.0.2');

define('TR_CMD_DELIMITER', ':');
define('TR_DATA_DELIMITER', '|');

// 게임 점수 투입
define('TR_CMD_CALL', 'F13');

// 배출 차단 제어
define('TR_CMD_CONTROL', 'F14');

// 응급 및 시스템 강제 제어
define('TR_CMD_EMERGENCY', 'EMG');
define('TR_ACT_PC_RESET', 'PC_RESET'); // 리부팅
define('TR_ACT_PC_OFF', 'PC_OFF'); // 전원종료
define('TR_ACT_GAME_KILL', 'GAME_KILL'); // 프로세스강제종료

// 정산 데이터 보고
define('TR_CMD_STATICS', 'STAT');

// 과금 및 결제 트랜잭션
define('TR_CMD_BILLING', 'BILL');

// 메시지 수신 확인 응답
define('TR_CMD_ACK', 'ACK');

?>