# Generated by gen_protocol.py - DO NOT EDIT DIRECTLY

PROJECT = "ThrillRig"
APP_VERSION = "0.0.2"

class TRProtocol:
    APP_VERSION = "0.0.2"
    CMD_DELIMITER = ":"
    DATA_DELIMITER = "|"

    # 게임 점수 투입
    CMD_CALL = "F13"

    # 배출 차단 제어
    CMD_CONTROL = "F14"

    # 응급 및 시스템 강제 제어
    CMD_EMERGENCY = "EMG"
    ACT_PC_RESET = "PC_RESET"  # 리부팅
    ACT_PC_OFF = "PC_OFF"  # 전원종료
    ACT_GAME_KILL = "GAME_KILL"  # 프로세스강제종료

    # 정산 데이터 보고
    CMD_STATICS = "STAT"

    # 과금 및 결제 트랜잭션
    CMD_BILLING = "BILL"

    # 메시지 수신 확인 응답
    CMD_ACK = "ACK"
